### ISSUE TITLE
游戏内的消息消息无法同步到QQ中

### ISSUE THREAD

**Issue by tiltysola** [ParaParty/JustChat#15]
什么错误提示都没有，其他功能均正常。就是游戏内说话QQ无法接受

**Comment by tiltysola** [comment]
服务端使用了: PaPI, NewHonor, UltimateChat插件，是Sponge1.12.2

**Comment by ExerciseBook** [comment]
查看一下酷Q的日志中是否正常。
如果日志中有发送成功的记录而实际上没有的话，那么大体可能是被腾讯风控了。

Sponge 的最新版是这个
https://github.com/ExerciseBook/JustChat/releases/tag/1.2.0


这个版本是有问题的一个测试版，**请勿使用**
https://github.com/ExerciseBook/JustChat/releases/tag/1.2.2-Alpha

如果还有问题的话再另外回复。

**Comment by tiltysola** [comment]
解决~

**Comment by ExerciseBook** [comment]
感谢您选择使用我的这个小插件 ❤️
