### ISSUE TITLE
部分设置和指令无效

### ISSUE THREAD

**Issue by ddaodan** [ParaParty/JustChat#17]
**描述这个错误**
1 机器人端修改设置没有效果，关闭玩家进出服务器信息仍然提示
2 玩家进出服务器的提示是英文（已在配置文件修改了中文，并且连接成功的提示是中文的）
3 群里发送/list，服务器后台提示收到未知类型的信息，游戏里显示/list

**复现**
通过以下的操作可以产生这个错误:
1. 打开 '...'
2. 按下 '....'
3. 下拉滚动 '....'
4. 发现错误

**期望的运行结果**

**截图**

**作业平台 (请务必完善本栏内容):**
1. 第一作业平台
	- 操作系统: [Windows Server 2016]
	- 运行平台: [Catserver]
	- 插件版本: [1.2.2]

**附加信息**

**Comment by ddaodan** [comment]
手机好像没有图，晚上我上传一下

**Comment by ddaodan** [comment]
手机传不了图。。。我晚上发一下

**Comment by ExerciseBook** [comment]
错误一错误二 提供一下配置文件内容
错误三 提供一下插件版本号

**Comment by ddaodan** [comment]
`config.ini`
[server]
ip=0.0.0.0
port=8282
mode=server

[config]
groupid=814526281

[events]
Info_all=true
Info_network=true
Info_playerDeath=ftrue
Info_other=ftrue
playerList=true

服务端插件版本1.1.2 机器人插件版本1.2.2

**Comment by ddaodan** [comment]
> 错误一错误二 提供一下配置文件内容
> 错误三 提供一下插件版本号

config.ini
[server]
ip=0.0.0.0
port=8282
mode=server

[config]
groupid=814526281

[events]
Info_all=true
Info_network=true
Info_playerDeath=ftrue
Info_other=ftrue
playerList=true

服务端插件版本1.1.2 机器人插件版本1.2.2

**Comment by ddaodan** [comment]
现在我把除了`Info_all`之外的都关闭了，倒是没有进出服务器的提示了

**Comment by ExerciseBook** [comment]
拼错了，是 false 。。。

**Comment by ddaodan** [comment]
> 拼错了，是 false 。。。

尴尬。。。发上来的时候没改好
是默认配置，端口都没有改

**Comment by ExerciseBook** [comment]
然后语言配置文件也可以康康。

**Comment by ddaodan** [comment]
[message]
Msg_INFO_General=[%SERVER%] %CONTENT%
Msg_INFO_Join=[%SERVER%] %SENDER% 进入游戏.
Msg_INFO_Disconnect=[%SERVER%] %SENDER% 退出游戏.
Msg_INFO_PlayerDead=[%SERVER%] %SENDER% 死了.
Msg_Text_Overview=[%SERVER%]%SENDER% >>> %CONTENT%
Event_online=服务器 %NAME% 连接成功.
Event_offline=服务器 %NAME% 已离线.
Msg_Server_Playerlist=[%SERVER%] 当前有 %NOW%/%MAX% 在线玩家.

编码utf8无bom

**Comment by ddaodan** [comment]
> 然后语言配置文件也可以康康。

当时是连接成功是用的这里的，但是进出服务器还是英文

**Comment by ExerciseBook** [comment]
看起来有点魔幻，改完配置文件后重启机器人了吗？

**Comment by ddaodan** [comment]
> 看起来有点魔幻，改完配置文件后重启机器人了吗？

重启过了的，聊天是没有问题的应该不是没连上的问题

**Comment by ExerciseBook** [comment]
刚刚在听报告，有段时间没看手机，抱歉。

的确奇怪，因为我没试出这个问题。

**Comment by ExerciseBook** [comment]
我思考了一下，我想起来问题所在了。

Bukkit的插件里会把mc服务器里的内容原封不动发到机器人那边，如果不出意外的话他就是默认的 “XXX joined the game” ，如果有需要改的话可以在mc服务器那边用其他插件修改。

**Comment by ExerciseBook** [comment]
增加相关配置字段以解决这个错误。下个版本发布。
