### ISSUE TITLE
[需求]彩色文本转发

### ISSUE THREAD

**Issue by LovelyCatHyt** [ParaParty/JustChat#18]
**你为什么想让我们添加这个功能？**
好康, 弥补了转发信息没有颜色的缺点
**描述你想要的效果**
QQ群:"&1Hi"
服务端:"/tellraw @?? {"text":"Hi","color":"blue"}"
*我忘记是@什么了*
**描述你想要的次选效果**
没有更次的选择了吧
**附加信息**
支持更复杂的转义, 如点击事件. 不过这样的话对群员的要求有点高.

**Comment by ExerciseBook** [comment]
![image](https://user-images.githubusercontent.com/6327311/75543453-c6fa3980-5a5c-11ea-9bdf-3b352241a0ea.png)
问题是你怎么说服腾讯加入QQ群内排版功能呢（

**Comment by LovelyCatHyt** [comment]
那就说服JustChat作者加入图片生成功能, 实现反向需求(

**Comment by ExerciseBook** [comment]
不想写排版系统
告辞.jpg
![image](https://user-images.githubusercontent.com/6327311/75838799-e5b45380-5e01-11ea-81c6-4a89c8ac4201.png)

**Comment by endymx** [comment]
不现实，QQ字体颜色不能这样改，爪巴
