### ISSUE TITLE
游戏内消息无法同步到QQ

### ISSUE THREAD

**Issue by OctoFlareDev** [ParaParty/JustChat#28]
**描述这个错误**
游戏内消息无法同步到QQ，QQ消息正常同步到游戏，酷Q内无报错，显示消息发送正常

**期望的运行结果**
两边消息互通

**作业平台 (请务必完善本栏内容):**
1. 第一作业平台
	- 操作系统: Windows 10 Professional Insider Preview Build 20170.rs_prerelease.200710-1419
	- 运行平台: Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
	- 插件版本: 2.0.0
	- 运行平台: CoolQ Air
	- 插件版本: 2.0.1

**Comment by ExerciseBook** [comment]
1. 检查一下酷Q日志中是否有绿色的消息已发送的日志。如果没有则跳第3。
2. 由于腾讯风控，你的机器人的消息被QQ拦下来了，具体见 https://docs.cqp.im/manual/faq/  。跳第4。
3. 检查一下用户权限是否正常赋予。
4. 没了。
