### ISSUE TITLE
QQ群的消息无法同步到游戏中

### ISSUE THREAD

**Issue by clm0081** [ParaParty/JustChat#3]
coolq插件装好了，游戏里的消息可以正常同步到QQ群里，但是群里的消息没办法同步到游戏中。

**Comment by clm0081** [comment]
用的是海绵服，装的1.1模组。

**Comment by clm0081** [comment]
还有，你写的那个QQ群号码，搜索不到。

**Comment by ExerciseBook** [comment]
没有复现本错误。
```
JustChat-Client-Sponge-1.1.0-all.jar
JustChat-ClientAndServer-CoolQ-1.1.3.zip
```
请检查机器人日志，查看QQ群聊发言信息是否被其他插件拦截。

![image](https://user-images.githubusercontent.com/6327311/52388045-8df4cd00-2ac7-11e9-84b5-698b6353e8f4.png)
果真如此请到事件列表中调整插件的优先顺序。

**Comment by clm0081** [comment]
已解决！确实是优先问题！
